$ANSIBLE_VAULT;1.1;AES256
66393937373935666134313465633137306236623438646664636539323237306331396335656232
3539373736396661623839376466356166653361313832340a656335346137313565653564613263
31353361663565393566346166336430333936393435366330626333633639303866663336643965
3534616664376565350a616234623836303337333238306361383938373130393864313334346632
30653030363938623861353135306339323664666631343166366364333932616137656430363030
6232643730646237363136653235396436373764373138643864
