---
# Handlers for dev_machine role

- name: restart podman
  systemd:
    name: podman
    state: restarted
    daemon_reload: yes
  when: dev_install_containers | bool

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
  when: dev_enable_ssh | bool
