---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart getty@tty1 service
  ansible.builtin.systemd:
    name: "getty@tty1.service"
    state: restarted
